---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, Gemfile*]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments


### content configuration ###
title:       "bootenv"
keywords:    "simple environment configuration management"
description: bootenv provides a simple service that makes it easy to setup configuration variables from a central server instead of hardcoding the values in configuration files.
source_link: "https://github.com/bootenv"
favicon:     "img/favicon.png"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  purple:    '#c869bf'
  color1:    '#49a7e9'
  color2:    '#9bcf2f'
  color3:    '#fab125'
  color4:    '#0fbfcf'
  color5:    '#80cf2c'
  
